
version: '3.1'

networks:
  rede_app:    
    driver: bridge
    
volumes:
  rinha:    

services:

  app01: &app
    image: swoole/postgres
    hostname: app01
    networks:
      rede_app:
        aliases:
          - app01
    environment:
      - DB_HOSTNAME=db
      - PORT=9000
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /var/www/
    deploy:
     resources:
       limits:
         cpus: '0.3'
         memory: '75MB'  

  app02:
    <<: *app
    hostname: app02    

  nginx:
    image: nginx
    restart: always
    networks:
      - rede_app
    ports:
      - 9999:80 
    depends_on:
      - app01
      - app02  
    deploy:
     resources:
       limits:
         cpus: "0.4"
         memory: "40MB"  
    volumes:
      - type: bind
        source: ./container/nginx/nginx.conf
        target: /etc/nginx/nginx.conf     

  db:
    image: postgres
    restart: always
    hostname: db
    networks:
      rede_app:
        aliases:
          - db
    environment:
      POSTGRES_PASSWORD: teste
    ports:
      - 5433:5432  
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "360MB"  
    volumes: 
      - rinha:/var/lib/postgresql/datas
      - ./container/script.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0 
